package org.tbwork.anole.common.model;

/**
 * @program: anole-common
 * @description:
 * @author: tommy.tb
 * @create: 2019-04-23 15:44
 **/
public class BaseRequest {

    /**
     * Global Id of Subscriber Client.
     */
    private int clientId;

    /**
     * Global token for certain clientId, which is
     * generated by the server against invalid connection.
     */
    private int token;
}
